theme: jekyll-theme-architect
# Site settings
title: 随手记下的感触
description: 喜欢我请联系我
author: kinfai
email: kinfai_yeong@outlook.com
...

---
author: kinfai 
comments: true
date: 2019-03-01
layout: post
title: 就当我在乱写
---
